all:
	pdflatex paper/paper
	mv paper.pdf sigplan_climate_data_analysis.pdf
	mv paper* paper

draft_Y:
	pdflatex draft_Yannick/old_draft
	mv old_draft.pdf draft_Yannick.pdf
	mv old_draft* draft_Yannick

draft_C:
	pdflatex draft_Crista/main
	mv main.pdf draft_Crista.pdf
	mv main* draft_Crista
